### ISSUE TITLE
please continue the work 

### ISSUE THREAD

**Issue by kerolloz** [flutter-webrtc/flutter-mediasoup-client#2]

**Comment by kerolloz** [comment]
I am ready to help with the project. please provide me with information how can I help

**Comment by cloudwebrtc** [comment]
@kerolloz We need to convert the code in https://github.com/versatica/libmediasoupclient/tree/v3/src to the dart version, and we may need to wait for flutter-webrtc to complete [Unified-Plan](https://github.com/cloudwebrtc/flutter-webrtc/issues/99), so the project is in a suspended state.

**Comment by hervejegou** [comment]
@cloudwebrtc thank you for your work so far. I know you have some other priorities. We are interested in a production ready flutter client for mediasoup. We are willing to contract your company to complete this if needed? please advise what we can do to help you, and please advise if you think this project could be completed in the next 30 days with additional resources ?

**Comment by tan-tan-kanarek** [comment]
+1

**Comment by KurdAppDev** [comment]
+1

**Comment by uzenith360** [comment]
+1

**Comment by cloudwebrtc** [comment]
Can continue now.
https://github.com/flutter-webrtc/flutter-webrtc/commit/11c1fd1137be6333c2252a20e999b2d6b53632db
